
INSERT INTO songs (artist, name, album, is_favorite) VALUES
('The Beatles', 'Let It Be', 'Let It Be', true),
('Queen', 'Bohemian Rhapsody', 'A Night at the Opera', true),
('Michael Jackson', 'Billie Jean', 'Thriller', true),
('Bob Dylan', 'Like a Rolling Stone', 'Highway 61 Revisited', false),
('Elton John', 'Rocket Man', 'Honky Château', false),
('Led Zeppelin', 'Stairway to Heaven', 'IV', true),
('Pink Floyd', 'Comfortably Numb', 'The Wall', true),
('U2', 'With or Without You', 'The Joshua Tree', true),
('Nirvana', 'Smells Like Teen Spirit', 'Nevermind', false),
('The Rolling Stones', 'Paint It Black', 'Aftermath', true),
('The Who', 'Baba O''Riley', 'Who''s Next', false),
('John Lennon', 'Imagine', 'Imagine', true),
('David Bowie', 'Space Oddity', 'David Bowie', false),
('The Eagles', 'Hotel California', 'Hotel California', true),
('Adele', 'Someone Like You', '21', true),
('Fleetwood Mac', 'Go Your Own Way', 'Rumours', false),
('Prince', 'Purple Rain', 'Purple Rain', true),
('The Police', 'Every Breath You Take', 'Synchronicity', false),
('The Doors', 'Light My Fire', 'The Doors', true),
('Johnny Cash', 'Ring of Fire', 'Ring of Fire: The Best of Johnny Cash', false),
('Radiohead', 'Creep', 'Pablo Honey', true),
('Whitney Houston', 'I Will Always Love You', 'The Bodyguard: Original Soundtrack Album', true),
('Elvis Presley', 'Can''t Help Falling in Love', 'Blue Hawaii', false),
('Journey', 'Don''t Stop Believin''', 'Escape', true),
('Madonna', 'Like a Virgin', 'Like a Virgin', false),
('The Beach Boys', 'Good Vibrations', 'Smiley Smile', true),
('Guns N'' Roses', 'Sweet Child o'' Mine', 'Appetite for Destruction', true),
('Aerosmith', 'Dream On', 'Aerosmith', false),
('Coldplay', 'Fix You', 'X&Y', true),
('Bee Gees', 'Stayin Alive', 'Saturday Night Fever: The Original Movie Sound Track', false);

-- Seed album data with real album titles and release dates
INSERT INTO albums (title, release_date) VALUES
  ('Abbey Road', '1969-09-26'),
  ('Thriller', '1982-11-30'),
  ('Dark Side of the Moon', '1973-03-01'),
  ('Rumours', '1977-02-04'),
  ('The Wall', '1979-11-30'),
  ('Back in Black', '1980-07-25'),
  ('Led Zeppelin IV', '1971-11-08'),
  ('Hotel California', '1976-12-08'),
  ('A Night at the Opera', '1975-11-21'),
  ('Sgt. Pepper''s Lonely Hearts Club Band', '1967-05-26'),
  ('The Joshua Tree', '1987-03-09'),
  ('Legend', '1984-05-08'),
  ('Let It Be', '1970-05-08'),
  ('Nevermind', '1991-09-24'),
  ('The Queen Is Dead', '1986-06-16'),
  ('OK Computer', '1997-05-21'),
  ('Born to Run', '1975-08-25'),
  ('The White Album', '1968-11-22'),
  ('A Hard Day''s Night', '1964-07-10'),
  ('The Doors', '1967-01-04'),
  ('Pet Sounds', '1966-05-16'),
  ('Breakfast in America', '1979-03-29'),
  ('Led Zeppelin II', '1969-10-22'),
  ('Abbey Road', '1969-09-26'),
  ('Who''s Next', '1971-08-14'),
  ('Innervisions', '1973-08-03'),
  ('The Stranger', '1977-09-29'),
  ('Songs in the Key of Life', '1976-09-28'),
  ('Off the Wall', '1979-08-10'),
  ('Bad', '1987-08-31'),
  ('The Queen Is Dead', '1986-06-16');
